[02/10/2023 09:03:41 AM][INFO][werkzeug]_internal.py[224]:_log() -> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5007
 * Running on http://192.168.50.108:5007
[02/10/2023 09:03:41 AM][INFO][werkzeug]_internal.py[224]:_log() -> [33mPress CTRL+C to quit[0m
[02/10/2023 09:03:58 AM][INFO][werkzeug]_internal.py[224]:_log() -> 127.0.0.1 - - [10/Feb/2023 09:03:58] "[32mGET / HTTP/1.1[0m" 302 -
[02/10/2023 09:03:59 AM][INFO][werkzeug]_internal.py[224]:_log() -> 127.0.0.1 - - [10/Feb/2023 09:03:59] "GET /login HTTP/1.1" 200 -
[02/10/2023 09:03:59 AM][INFO][werkzeug]_internal.py[224]:_log() -> 127.0.0.1 - - [10/Feb/2023 09:03:59] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[02/10/2023 09:16:19 AM][INFO][werkzeug]_internal.py[224]:_log() -> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5007
 * Running on http://192.168.50.108:5007
[02/10/2023 09:16:19 AM][INFO][werkzeug]_internal.py[224]:_log() -> [33mPress CTRL+C to quit[0m
[02/10/2023 09:16:31 AM][INFO][werkzeug]_internal.py[224]:_log() -> 127.0.0.1 - - [10/Feb/2023 09:16:31] "[32mGET / HTTP/1.1[0m" 302 -
[02/10/2023 09:16:31 AM][INFO][werkzeug]_internal.py[224]:_log() -> 127.0.0.1 - - [10/Feb/2023 09:16:31] "GET /login HTTP/1.1" 200 -
[02/10/2023 09:16:31 AM][INFO][werkzeug]_internal.py[224]:_log() -> 127.0.0.1 - - [10/Feb/2023 09:16:31] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[02/10/2023 09:20:22 AM][INFO][werkzeug]_internal.py[224]:_log() -> 127.0.0.1 - - [10/Feb/2023 09:20:22] "[32mGET / HTTP/1.1[0m" 302 -
[02/10/2023 09:20:22 AM][INFO][werkzeug]_internal.py[224]:_log() -> 127.0.0.1 - - [10/Feb/2023 09:20:22] "GET /login HTTP/1.1" 200 -
[02/10/2023 09:20:42 AM][INFO][werkzeug]_internal.py[224]:_log() -> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5007
 * Running on http://192.168.50.108:5007
[02/10/2023 09:20:42 AM][INFO][werkzeug]_internal.py[224]:_log() -> [33mPress CTRL+C to quit[0m
[02/10/2023 09:20:53 AM][INFO][werkzeug]_internal.py[224]:_log() -> 127.0.0.1 - - [10/Feb/2023 09:20:53] "GET /register HTTP/1.1" 200 -
[02/10/2023 09:21:45 AM][ERROR][server]app.py[1741]:log_exception() -> Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\v3\server.py", line 123, in register
    db.session.commit()
  File "<string>", line 2, in commit
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3444, in flush
    self._flush(objects)
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3583, in _flush
    with util.safe_reraise():
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3544, in _flush
    flush_context.execute()
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: INSERT INTO user (username, password) VALUES (?, ?)]
[parameters: ('charleshparmley@icloud.com', 'Earthday19!@22')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[02/10/2023 09:21:45 AM][INFO][werkzeug]_internal.py[224]:_log() -> 127.0.0.1 - - [10/Feb/2023 09:21:45] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
[02/10/2023 09:22:27 AM][INFO][werkzeug]_internal.py[224]:_log() -> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5007
 * Running on http://192.168.50.108:5007
[02/10/2023 09:22:27 AM][INFO][werkzeug]_internal.py[224]:_log() -> [33mPress CTRL+C to quit[0m
[02/10/2023 09:22:52 AM][ERROR][server]app.py[1741]:log_exception() -> Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\v3\server.py", line 123, in register
    db.session.commit()
  File "<string>", line 2, in commit
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3444, in flush
    self._flush(objects)
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3583, in _flush
    with util.safe_reraise():
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3544, in _flush
    flush_context.execute()
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\H\Documents\auto7shifts\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: INSERT INTO user (username, password) VALUES (?, ?)]
[parameters: ('charleshparmley@icloud.com', 'Earthday19!@22')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[02/10/2023 09:22:52 AM][INFO][werkzeug]_internal.py[224]:_log() -> 127.0.0.1 - - [10/Feb/2023 09:22:52] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
[02/11/2023 09:10:37 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:10:38 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:10:40 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Email'
[02/11/2023 09:10:44 PM][INFO][root]cli.py[153]:set_username() -> Email set
[02/11/2023 09:10:44 PM][DEBUG][root]cli.py[154]:set_username() -> account.email='charleshparmley@icloud.com'
[02/11/2023 09:10:44 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:10:46 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:10:47 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Password'
[02/11/2023 09:10:51 PM][INFO][root]cli.py[161]:set_userpass() -> Password set
[02/11/2023 09:10:51 PM][DEBUG][root]cli.py[162]:set_userpass() -> account.password='Earthday19!@22'
[02/11/2023 09:10:51 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:10:52 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:10:53 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Submit'
[02/11/2023 09:11:33 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:11:34 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:11:35 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Email'
[02/11/2023 09:11:41 PM][INFO][root]cli.py[153]:set_username() -> Email set
[02/11/2023 09:11:41 PM][DEBUG][root]cli.py[154]:set_username() -> account.email='charleshparmley@icloud.com'
[02/11/2023 09:11:41 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:11:42 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:11:43 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Password'
[02/11/2023 09:11:49 PM][INFO][root]cli.py[161]:set_userpass() -> Password set
[02/11/2023 09:11:49 PM][DEBUG][root]cli.py[162]:set_userpass() -> account.password='Earthday19!@22'
[02/11/2023 09:11:49 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:11:50 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:11:51 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Submit'
[02/11/2023 09:11:51 PM][DEBUG][urllib3.connectionpool]connectionpool.py[1003]:_new_conn() -> Starting new HTTPS connection (1): app.7shifts.com:443
[02/11/2023 09:11:52 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /users/login HTTP/1.1" 302 None
[02/11/2023 09:11:52 PM][INFO][root]scraper.py[79]:_login() -> Loggin Success
[02/11/2023 09:11:52 PM][INFO][root]scraper.py[89]:_read_user_info() -> Updating Account Data
[02/11/2023 09:11:52 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v2/company/254692/account HTTP/1.1" 200 None
[02/11/2023 09:11:52 PM][DEBUG][root]scraper.py[111]:_update_session_info() -> Updataing Session Info
[02/11/2023 09:11:52 PM][DEBUG][root]scraper.py[112]:_update_session_info() -> self.user_id=6053191
self.email='charleshparmley@icloud.com'
[02/11/2023 09:11:52 PM][INFO][root]scraper.py[120]:_read_user_schedule() -> Updating Scheduled Days
[02/11/2023 09:11:52 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v1/schedule/shifts?week=2023-02-11&location_id=319579&department_id=464752 HTTP/1.1" 200 None
[02/11/2023 09:11:52 PM][DEBUG][root]scraper.py[148]:_update_session_schedule() -> Updating Session Schedule
[02/11/2023 09:11:52 PM][DEBUG][root]scraper.py[149]:_update_session_schedule() -> Currently Scheduled: []
[02/11/2023 09:11:52 PM][INFO][root]scraper.py[157]:_read_user_pool() -> Updating Shift Pool
[02/11/2023 09:11:53 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /gql HTTP/1.1" 400 2094
[02/11/2023 09:11:53 PM][DEBUG][root]scraper.py[178]:_update_session_pool() -> Shift Pool: {'errors': [{'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 5, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Cursor".', 'locations': [{'line': 11, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolResponse".', 'locations': [{'line': 13, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolEmployee".', 'locations': [{'line': 27, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPool".', 'locations': [{'line': 29, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Contact".', 'locations': [{'line': 42, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 48, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Department".', 'locations': [{'line': 52, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Role".', 'locations': [{'line': 58, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolShift".', 'locations': [{'line': 60, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 65, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolBid".', 'locations': [{'line': 70, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 72, 'column': 3}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}]}
[02/11/2023 09:11:53 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:11:53 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:12:56 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:12:58 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:12:59 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Email'
[02/11/2023 09:13:04 PM][INFO][root]cli.py[153]:set_username() -> Email set
[02/11/2023 09:13:04 PM][DEBUG][root]cli.py[154]:set_username() -> account.email='charleshparmley@icloud.com'
[02/11/2023 09:13:04 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:13:05 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:13:06 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Password'
[02/11/2023 09:13:09 PM][INFO][root]cli.py[161]:set_userpass() -> Password set
[02/11/2023 09:13:09 PM][DEBUG][root]cli.py[162]:set_userpass() -> account.password='Earthday19!@22'
[02/11/2023 09:13:09 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:13:11 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:13:11 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Submit'
[02/11/2023 09:13:11 PM][DEBUG][urllib3.connectionpool]connectionpool.py[1003]:_new_conn() -> Starting new HTTPS connection (1): app.7shifts.com:443
[02/11/2023 09:13:12 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /users/login HTTP/1.1" 302 None
[02/11/2023 09:13:12 PM][INFO][root]scraper.py[79]:_login() -> Loggin Success
[02/11/2023 09:13:12 PM][INFO][root]scraper.py[89]:_read_user_info() -> Updating Account Data
[02/11/2023 09:13:12 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v2/company/254692/account HTTP/1.1" 200 None
[02/11/2023 09:13:12 PM][DEBUG][root]scraper.py[111]:_update_session_info() -> Updataing Session Info
[02/11/2023 09:13:12 PM][DEBUG][root]scraper.py[112]:_update_session_info() -> self.user_id=6053191
self.email='charleshparmley@icloud.com'
[02/11/2023 09:13:12 PM][INFO][root]scraper.py[120]:_read_user_schedule() -> Updating Scheduled Days
[02/11/2023 09:13:12 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v1/schedule/shifts?week=2023-02-11&location_id=319579&department_id=464752 HTTP/1.1" 200 None
[02/11/2023 09:13:12 PM][DEBUG][root]scraper.py[148]:_update_session_schedule() -> Updating Session Schedule
[02/11/2023 09:13:12 PM][DEBUG][root]scraper.py[149]:_update_session_schedule() -> Currently Scheduled: []
[02/11/2023 09:13:12 PM][INFO][root]scraper.py[157]:_read_user_pool() -> Updating Shift Pool
[02/11/2023 09:13:13 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /gql HTTP/1.1" 400 2094
[02/11/2023 09:13:13 PM][DEBUG][root]scraper.py[178]:_update_session_pool() -> Shift Pool: {'errors': [{'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 5, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Cursor".', 'locations': [{'line': 11, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolResponse".', 'locations': [{'line': 13, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolEmployee".', 'locations': [{'line': 27, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPool".', 'locations': [{'line': 29, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Contact".', 'locations': [{'line': 42, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 48, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Department".', 'locations': [{'line': 52, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Role".', 'locations': [{'line': 58, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolShift".', 'locations': [{'line': 60, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 65, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolBid".', 'locations': [{'line': 70, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 72, 'column': 3}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}]}
[02/11/2023 09:13:13 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:13:13 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:13:34 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:13:35 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:13:36 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Email'
[02/11/2023 09:13:42 PM][INFO][root]cli.py[153]:set_username() -> Email set
[02/11/2023 09:13:42 PM][DEBUG][root]cli.py[154]:set_username() -> account.email='charleshparmley@icloud.com'
[02/11/2023 09:13:42 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:13:43 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:13:44 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Password'
[02/11/2023 09:13:46 PM][INFO][root]cli.py[161]:set_userpass() -> Password set
[02/11/2023 09:13:46 PM][DEBUG][root]cli.py[162]:set_userpass() -> account.password='Earthday19!@22'
[02/11/2023 09:13:46 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:13:47 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:13:48 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Submit'
[02/11/2023 09:13:48 PM][DEBUG][urllib3.connectionpool]connectionpool.py[1003]:_new_conn() -> Starting new HTTPS connection (1): app.7shifts.com:443
[02/11/2023 09:13:48 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /users/login HTTP/1.1" 302 None
[02/11/2023 09:13:48 PM][INFO][root]scraper.py[79]:_login() -> Loggin Success
[02/11/2023 09:13:48 PM][INFO][root]scraper.py[89]:_read_user_info() -> Updating Account Data
[02/11/2023 09:13:49 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v2/company/254692/account HTTP/1.1" 200 None
[02/11/2023 09:13:49 PM][DEBUG][root]scraper.py[111]:_update_session_info() -> Updataing Session Info
[02/11/2023 09:13:49 PM][DEBUG][root]scraper.py[112]:_update_session_info() -> self.user_id=6053191
self.email='charleshparmley@icloud.com'
[02/11/2023 09:13:49 PM][INFO][root]scraper.py[120]:_read_user_schedule() -> Updating Scheduled Days
[02/11/2023 09:13:49 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v1/schedule/shifts?week=2023-02-11&location_id=319579&department_id=464752 HTTP/1.1" 200 None
[02/11/2023 09:13:49 PM][DEBUG][root]scraper.py[148]:_update_session_schedule() -> Updating Session Schedule
[02/11/2023 09:13:49 PM][DEBUG][root]scraper.py[149]:_update_session_schedule() -> Currently Scheduled: []
[02/11/2023 09:13:49 PM][INFO][root]scraper.py[157]:_read_user_pool() -> Updating Shift Pool
[02/11/2023 09:13:49 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /gql HTTP/1.1" 400 2094
[02/11/2023 09:13:49 PM][DEBUG][root]scraper.py[178]:_update_session_pool() -> Shift Pool: {'errors': [{'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 5, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Cursor".', 'locations': [{'line': 11, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolResponse".', 'locations': [{'line': 13, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolEmployee".', 'locations': [{'line': 27, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPool".', 'locations': [{'line': 29, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Contact".', 'locations': [{'line': 42, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 48, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Department".', 'locations': [{'line': 52, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Role".', 'locations': [{'line': 58, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolShift".', 'locations': [{'line': 60, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 65, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolBid".', 'locations': [{'line': 70, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 72, 'column': 3}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}]}
[02/11/2023 09:13:49 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:13:49 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:14:11 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:14:12 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:14:12 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Email'
[02/11/2023 09:14:16 PM][INFO][root]cli.py[153]:set_username() -> Email set
[02/11/2023 09:14:16 PM][DEBUG][root]cli.py[154]:set_username() -> account.email='charleshparmley@icloud.com'
[02/11/2023 09:14:16 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:14:18 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:14:19 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Password'
[02/11/2023 09:14:22 PM][INFO][root]cli.py[161]:set_userpass() -> Password set
[02/11/2023 09:14:22 PM][DEBUG][root]cli.py[162]:set_userpass() -> account.password='Earthday19!@22'
[02/11/2023 09:14:22 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:14:23 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:14:24 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Submit'
[02/11/2023 09:14:24 PM][DEBUG][urllib3.connectionpool]connectionpool.py[1003]:_new_conn() -> Starting new HTTPS connection (1): app.7shifts.com:443
[02/11/2023 09:14:24 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /users/login HTTP/1.1" 302 None
[02/11/2023 09:14:24 PM][INFO][root]scraper.py[79]:_login() -> Loggin Success
[02/11/2023 09:14:24 PM][INFO][root]scraper.py[89]:_read_user_info() -> Updating Account Data
[02/11/2023 09:14:24 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v2/company/254692/account HTTP/1.1" 200 None
[02/11/2023 09:14:24 PM][DEBUG][root]scraper.py[111]:_update_session_info() -> Updataing Session Info
[02/11/2023 09:14:24 PM][DEBUG][root]scraper.py[112]:_update_session_info() -> self.user_id=6053191
self.email='charleshparmley@icloud.com'
[02/11/2023 09:14:24 PM][INFO][root]scraper.py[120]:_read_user_schedule() -> Updating Scheduled Days
[02/11/2023 09:14:25 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v1/schedule/shifts?week=2023-02-11&location_id=319579&department_id=464752 HTTP/1.1" 200 None
[02/11/2023 09:14:25 PM][DEBUG][root]scraper.py[148]:_update_session_schedule() -> Updating Session Schedule
[02/11/2023 09:14:25 PM][DEBUG][root]scraper.py[149]:_update_session_schedule() -> Currently Scheduled: []
[02/11/2023 09:14:25 PM][INFO][root]scraper.py[157]:_read_user_pool() -> Updating Shift Pool
[02/11/2023 09:14:25 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /gql HTTP/1.1" 400 2094
[02/11/2023 09:14:25 PM][DEBUG][root]scraper.py[178]:_update_session_pool() -> Shift Pool: {'errors': [{'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 5, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Cursor".', 'locations': [{'line': 11, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolResponse".', 'locations': [{'line': 13, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolEmployee".', 'locations': [{'line': 27, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPool".', 'locations': [{'line': 29, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Contact".', 'locations': [{'line': 42, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 48, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Department".', 'locations': [{'line': 52, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Role".', 'locations': [{'line': 58, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolShift".', 'locations': [{'line': 60, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 65, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolBid".', 'locations': [{'line': 70, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 72, 'column': 3}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}]}
[02/11/2023 09:14:25 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:14:25 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:14:40 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:14:41 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:14:41 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Email'
[02/11/2023 09:14:45 PM][INFO][root]cli.py[153]:set_username() -> Email set
[02/11/2023 09:14:45 PM][DEBUG][root]cli.py[154]:set_username() -> account.email='charleshparmley@icloud.com'
[02/11/2023 09:14:45 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:14:46 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:14:47 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Password'
[02/11/2023 09:14:50 PM][INFO][root]cli.py[161]:set_userpass() -> Password set
[02/11/2023 09:14:50 PM][DEBUG][root]cli.py[162]:set_userpass() -> account.password='Earthday19!@22'
[02/11/2023 09:14:50 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:14:51 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:14:52 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Submit'
[02/11/2023 09:14:52 PM][DEBUG][urllib3.connectionpool]connectionpool.py[1003]:_new_conn() -> Starting new HTTPS connection (1): app.7shifts.com:443
[02/11/2023 09:14:52 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /users/login HTTP/1.1" 302 None
[02/11/2023 09:14:52 PM][INFO][root]scraper.py[79]:_login() -> Loggin Success
[02/11/2023 09:14:52 PM][INFO][root]scraper.py[89]:_read_user_info() -> Updating Account Data
[02/11/2023 09:14:52 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v2/company/254692/account HTTP/1.1" 200 None
[02/11/2023 09:14:52 PM][DEBUG][root]scraper.py[111]:_update_session_info() -> Updataing Session Info
[02/11/2023 09:14:52 PM][DEBUG][root]scraper.py[112]:_update_session_info() -> self.user_id=6053191
self.email='charleshparmley@icloud.com'
[02/11/2023 09:14:52 PM][INFO][root]scraper.py[120]:_read_user_schedule() -> Updating Scheduled Days
[02/11/2023 09:14:53 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v1/schedule/shifts?week=2023-02-11&location_id=319579&department_id=464752 HTTP/1.1" 200 None
[02/11/2023 09:14:53 PM][DEBUG][root]scraper.py[148]:_update_session_schedule() -> Updating Session Schedule
[02/11/2023 09:14:53 PM][DEBUG][root]scraper.py[149]:_update_session_schedule() -> Currently Scheduled: []
[02/11/2023 09:14:53 PM][INFO][root]scraper.py[157]:_read_user_pool() -> Updating Shift Pool
[02/11/2023 09:14:53 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /gql HTTP/1.1" 400 2094
[02/11/2023 09:14:53 PM][DEBUG][root]scraper.py[178]:_update_session_pool() -> Shift Pool: {'errors': [{'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 5, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Cursor".', 'locations': [{'line': 11, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolResponse".', 'locations': [{'line': 13, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolEmployee".', 'locations': [{'line': 27, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPool".', 'locations': [{'line': 29, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Contact".', 'locations': [{'line': 42, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 48, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Department".', 'locations': [{'line': 52, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Role".', 'locations': [{'line': 58, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolShift".', 'locations': [{'line': 60, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 65, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolBid".', 'locations': [{'line': 70, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 72, 'column': 3}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}]}
[02/11/2023 09:14:53 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:14:53 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:15:23 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:15:24 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:15:24 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Email'
[02/11/2023 09:15:28 PM][INFO][root]cli.py[153]:set_username() -> Email set
[02/11/2023 09:15:28 PM][DEBUG][root]cli.py[154]:set_username() -> account.email='charleshparmley@icloud.com'
[02/11/2023 09:15:28 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:15:29 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:15:30 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Password'
[02/11/2023 09:15:33 PM][INFO][root]cli.py[161]:set_userpass() -> Password set
[02/11/2023 09:15:33 PM][DEBUG][root]cli.py[162]:set_userpass() -> account.password='Earthday19!@22'
[02/11/2023 09:15:33 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:15:34 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:15:35 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Submit'
[02/11/2023 09:15:35 PM][DEBUG][urllib3.connectionpool]connectionpool.py[1003]:_new_conn() -> Starting new HTTPS connection (1): app.7shifts.com:443
[02/11/2023 09:15:35 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /users/login HTTP/1.1" 302 None
[02/11/2023 09:15:35 PM][INFO][root]scraper.py[79]:_login() -> Loggin Success
[02/11/2023 09:15:35 PM][INFO][root]scraper.py[89]:_read_user_info() -> Updating Account Data
[02/11/2023 09:15:35 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v2/company/254692/account HTTP/1.1" 200 None
[02/11/2023 09:15:35 PM][DEBUG][root]scraper.py[111]:_update_session_info() -> Updataing Session Info
[02/11/2023 09:15:35 PM][DEBUG][root]scraper.py[112]:_update_session_info() -> self.user_id=6053191
self.email='charleshparmley@icloud.com'
[02/11/2023 09:15:35 PM][INFO][root]scraper.py[120]:_read_user_schedule() -> Updating Scheduled Days
[02/11/2023 09:15:36 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v1/schedule/shifts?week=2023-02-11&location_id=319579&department_id=464752 HTTP/1.1" 200 None
[02/11/2023 09:15:36 PM][DEBUG][root]scraper.py[148]:_update_session_schedule() -> Updating Session Schedule
[02/11/2023 09:15:36 PM][DEBUG][root]scraper.py[149]:_update_session_schedule() -> Currently Scheduled: []
[02/11/2023 09:15:36 PM][INFO][root]scraper.py[157]:_read_user_pool() -> Updating Shift Pool
[02/11/2023 09:15:36 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /gql HTTP/1.1" 400 2094
[02/11/2023 09:15:36 PM][DEBUG][root]scraper.py[178]:_update_session_pool() -> Shift Pool: {'errors': [{'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 5, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Cursor".', 'locations': [{'line': 11, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolResponse".', 'locations': [{'line': 13, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolEmployee".', 'locations': [{'line': 27, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPool".', 'locations': [{'line': 29, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Contact".', 'locations': [{'line': 42, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 48, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Department".', 'locations': [{'line': 52, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Role".', 'locations': [{'line': 58, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolShift".', 'locations': [{'line': 60, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 65, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolBid".', 'locations': [{'line': 70, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 72, 'column': 3}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}]}
[02/11/2023 09:15:36 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:15:36 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:15:36 PM][DEBUG][root]cli.py[51]:preferences_menu() -> [None, None, None]
[02/11/2023 09:15:46 PM][DEBUG][root]cli.py[65]:preferences_menu() -> terminal_menu.chosen_menu_index=0
[02/11/2023 09:15:46 PM][DEBUG][root]cli.py[81]:get_selections() -> possible_values=['Server', 'Host', 'Manager', 'Cook', 'Dishwasher', 'Manager']
[02/11/2023 09:15:46 PM][DEBUG][root]cli.py[92]:get_selections() -> user_preferences[category]=None
[02/11/2023 09:15:52 PM][DEBUG][root]cli.py[96]:get_selections() -> user_preferences={'roles': ['Server'], 'days': None, 'locations': None}
[02/11/2023 09:15:52 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:15:52 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:15:52 PM][DEBUG][root]cli.py[51]:preferences_menu() -> [['Server'], None, None]
[02/11/2023 09:15:54 PM][DEBUG][root]cli.py[65]:preferences_menu() -> terminal_menu.chosen_menu_index=1
[02/11/2023 09:15:54 PM][DEBUG][root]cli.py[81]:get_selections() -> possible_values=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
[02/11/2023 09:15:54 PM][DEBUG][root]cli.py[92]:get_selections() -> user_preferences[category]=None
[02/11/2023 09:15:55 PM][DEBUG][root]cli.py[96]:get_selections() -> user_preferences={'roles': ['Server'], 'days': ['Friday'], 'locations': None}
[02/11/2023 09:15:55 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:15:55 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:15:55 PM][DEBUG][root]cli.py[51]:preferences_menu() -> [['Server'], ['Friday'], None]
[02/11/2023 09:15:56 PM][DEBUG][root]cli.py[65]:preferences_menu() -> terminal_menu.chosen_menu_index=2
[02/11/2023 09:15:56 PM][DEBUG][root]cli.py[81]:get_selections() -> possible_values=['Test Resturant']
[02/11/2023 09:15:56 PM][DEBUG][root]cli.py[92]:get_selections() -> user_preferences[category]=None
[02/11/2023 09:15:57 PM][DEBUG][root]cli.py[96]:get_selections() -> user_preferences={'roles': ['Server'], 'days': ['Friday'], 'locations': ['Test Resturant']}
[02/11/2023 09:15:57 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:15:57 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:15:57 PM][DEBUG][root]cli.py[51]:preferences_menu() -> [['Server'], ['Friday'], ['Test Resturant']]
[02/11/2023 09:16:00 PM][DEBUG][root]cli.py[65]:preferences_menu() -> terminal_menu.chosen_menu_index=2
[02/11/2023 09:16:00 PM][DEBUG][root]cli.py[81]:get_selections() -> possible_values=['Test Resturant']
[02/11/2023 09:16:00 PM][DEBUG][root]cli.py[92]:get_selections() -> user_preferences[category]=['Test Resturant']
[02/11/2023 09:16:01 PM][DEBUG][root]cli.py[96]:get_selections() -> user_preferences={'roles': ['Server'], 'days': ['Friday'], 'locations': ['Test Resturant']}
[02/11/2023 09:16:01 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:16:01 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:16:01 PM][DEBUG][root]cli.py[51]:preferences_menu() -> [['Server'], ['Friday'], ['Test Resturant']]
[02/11/2023 09:16:02 PM][DEBUG][root]cli.py[65]:preferences_menu() -> terminal_menu.chosen_menu_index=2
[02/11/2023 09:16:02 PM][DEBUG][root]cli.py[81]:get_selections() -> possible_values=['Test Resturant']
[02/11/2023 09:16:02 PM][DEBUG][root]cli.py[92]:get_selections() -> user_preferences[category]=['Test Resturant']
[02/11/2023 09:16:03 PM][DEBUG][root]cli.py[96]:get_selections() -> user_preferences={'roles': ['Server'], 'days': ['Friday'], 'locations': ['Test Resturant']}
[02/11/2023 09:16:03 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:16:03 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:16:03 PM][DEBUG][root]cli.py[51]:preferences_menu() -> [['Server'], ['Friday'], ['Test Resturant']]
[02/11/2023 09:16:04 PM][DEBUG][root]cli.py[65]:preferences_menu() -> terminal_menu.chosen_menu_index=1
[02/11/2023 09:16:04 PM][DEBUG][root]cli.py[81]:get_selections() -> possible_values=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
[02/11/2023 09:16:04 PM][DEBUG][root]cli.py[92]:get_selections() -> user_preferences[category]=['Friday']
[02/11/2023 09:16:09 PM][DEBUG][root]cli.py[96]:get_selections() -> user_preferences={'roles': ['Server'], 'days': ['Wednesday'], 'locations': ['Test Resturant']}
[02/11/2023 09:16:09 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:16:09 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:16:09 PM][DEBUG][root]cli.py[51]:preferences_menu() -> [['Server'], ['Wednesday'], ['Test Resturant']]
[02/11/2023 09:16:50 PM][DEBUG][root]cli.py[65]:preferences_menu() -> terminal_menu.chosen_menu_index=3
[02/11/2023 09:16:50 PM][DEBUG][urllib3.connectionpool]connectionpool.py[1003]:_new_conn() -> Starting new HTTPS connection (1): app.7shifts.com:443
[02/11/2023 09:16:50 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /users/login HTTP/1.1" 302 None
[02/11/2023 09:16:50 PM][INFO][root]scraper.py[79]:_login() -> Loggin Success
[02/11/2023 09:16:50 PM][INFO][root]scraper.py[89]:_read_user_info() -> Updating Account Data
[02/11/2023 09:16:51 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v2/company/254692/account HTTP/1.1" 200 None
[02/11/2023 09:16:51 PM][DEBUG][root]scraper.py[111]:_update_session_info() -> Updataing Session Info
[02/11/2023 09:16:51 PM][DEBUG][root]scraper.py[112]:_update_session_info() -> self.user_id=6053191
self.email='charleshparmley@icloud.com'
[02/11/2023 09:16:51 PM][INFO][root]scraper.py[120]:_read_user_schedule() -> Updating Scheduled Days
[02/11/2023 09:16:51 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v1/schedule/shifts?week=2023-02-11&location_id=319579&department_id=464752 HTTP/1.1" 200 None
[02/11/2023 09:16:51 PM][DEBUG][root]scraper.py[148]:_update_session_schedule() -> Updating Session Schedule
[02/11/2023 09:16:51 PM][DEBUG][root]scraper.py[149]:_update_session_schedule() -> Currently Scheduled: []
[02/11/2023 09:16:51 PM][INFO][root]scraper.py[157]:_read_user_pool() -> Updating Shift Pool
[02/11/2023 09:16:51 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /gql HTTP/1.1" 400 2094
[02/11/2023 09:16:51 PM][DEBUG][root]scraper.py[178]:_update_session_pool() -> Shift Pool: {'errors': [{'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 5, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Cursor".', 'locations': [{'line': 11, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolResponse".', 'locations': [{'line': 13, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolEmployee".', 'locations': [{'line': 27, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPool".', 'locations': [{'line': 29, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Contact".', 'locations': [{'line': 42, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 48, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Department".', 'locations': [{'line': 52, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Role".', 'locations': [{'line': 58, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolShift".', 'locations': [{'line': 60, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 65, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolBid".', 'locations': [{'line': 70, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 72, 'column': 3}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}]}
[02/11/2023 09:16:51 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v1/users?deep=1&offset=0&active=0 HTTP/1.1" 200 None
[02/11/2023 09:16:52 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v1/users?deep=1&offset=0&active=1 HTTP/1.1" 200 None
[02/11/2023 09:16:52 PM][DEBUG][root]server.py[227]:write_employees() -> Employee already exists
[02/11/2023 09:16:52 PM][DEBUG][root]server.py[227]:write_employees() -> Employee already exists
[02/11/2023 09:16:52 PM][DEBUG][root]server.py[227]:write_employees() -> Employee already exists
[02/11/2023 09:16:52 PM][DEBUG][root]server.py[227]:write_employees() -> Employee already exists
[02/11/2023 09:16:52 PM][DEBUG][root]server.py[227]:write_employees() -> Employee already exists
[02/11/2023 09:24:40 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:24:42 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:24:42 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Email'
[02/11/2023 09:24:46 PM][INFO][root]cli.py[153]:set_username() -> Email set
[02/11/2023 09:24:46 PM][DEBUG][root]cli.py[154]:set_username() -> account.email='charleshparmley@icloud.com'
[02/11/2023 09:24:46 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:24:46 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:24:47 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Password'
[02/11/2023 09:24:50 PM][INFO][root]cli.py[161]:set_userpass() -> Password set
[02/11/2023 09:24:50 PM][DEBUG][root]cli.py[162]:set_userpass() -> account.password='Earthday19!@22'
[02/11/2023 09:24:50 PM][INFO][root]cli.py[141]:verify_login() -> User not logged in
[02/11/2023 09:24:51 PM][DEBUG][root]cli.py[36]:main_menu() -> options[menu_entry_index]='Login'
[02/11/2023 09:24:51 PM][DEBUG][root]cli.py[127]:login_menu() -> options[menu_entry_index]='Submit'
[02/11/2023 09:24:51 PM][DEBUG][urllib3.connectionpool]connectionpool.py[1003]:_new_conn() -> Starting new HTTPS connection (1): app.7shifts.com:443
[02/11/2023 09:24:52 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /users/login HTTP/1.1" 302 None
[02/11/2023 09:24:52 PM][INFO][root]scraper.py[79]:_login() -> Loggin Success
[02/11/2023 09:24:52 PM][INFO][root]scraper.py[89]:_read_user_info() -> Updating Account Data
[02/11/2023 09:24:52 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v2/company/254692/account HTTP/1.1" 200 None
[02/11/2023 09:24:52 PM][DEBUG][root]scraper.py[111]:_update_session_info() -> Updataing Session Info
[02/11/2023 09:24:52 PM][DEBUG][root]scraper.py[112]:_update_session_info() -> self.user_id=6053191
self.email='charleshparmley@icloud.com'
[02/11/2023 09:24:52 PM][INFO][root]scraper.py[120]:_read_user_schedule() -> Updating Scheduled Days
[02/11/2023 09:24:53 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "GET /api/v1/schedule/shifts?week=2023-02-11&location_id=319579&department_id=464752 HTTP/1.1" 200 None
[02/11/2023 09:24:53 PM][DEBUG][root]scraper.py[148]:_update_session_schedule() -> Updating Session Schedule
[02/11/2023 09:24:53 PM][DEBUG][root]scraper.py[149]:_update_session_schedule() -> Currently Scheduled: []
[02/11/2023 09:24:53 PM][INFO][root]scraper.py[157]:_read_user_pool() -> Updating Shift Pool
[02/11/2023 09:24:53 PM][DEBUG][urllib3.connectionpool]connectionpool.py[456]:_make_request() -> https://app.7shifts.com:443 "POST /gql HTTP/1.1" 400 2094
[02/11/2023 09:24:53 PM][DEBUG][root]scraper.py[178]:_update_session_pool() -> Shift Pool: {'errors': [{'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 5, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Cursor".', 'locations': [{'line': 11, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolResponse".', 'locations': [{'line': 13, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolEmployee".', 'locations': [{'line': 27, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPool".', 'locations': [{'line': 29, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Contact".', 'locations': [{'line': 42, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 48, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Department".', 'locations': [{'line': 52, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Role".', 'locations': [{'line': 58, 'column': 7}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "ShiftPoolShift".', 'locations': [{'line': 60, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "Location".', 'locations': [{'line': 65, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolBid".', 'locations': [{'line': 70, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}, {'message': 'Cannot query field "_typename" on type "LegacyShiftPoolOffer".', 'locations': [{'line': 72, 'column': 3}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}]}
[02/11/2023 09:24:53 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:24:53 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:24:53 PM][DEBUG][root]cli.py[51]:preferences_menu() -> [None, None, None]
[02/11/2023 09:24:54 PM][DEBUG][root]cli.py[65]:preferences_menu() -> terminal_menu.chosen_menu_index=0
[02/11/2023 09:24:54 PM][DEBUG][root]cli.py[81]:get_selections() -> possible_values=['Server', 'Host', 'Manager', 'Cook', 'Dishwasher', 'Manager']
[02/11/2023 09:24:54 PM][DEBUG][root]cli.py[92]:get_selections() -> user_preferences[category]=None
[02/11/2023 09:24:54 PM][DEBUG][root]cli.py[96]:get_selections() -> user_preferences={'roles': ['Server'], 'days': None, 'locations': None}
[02/11/2023 09:24:54 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:24:54 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:24:54 PM][DEBUG][root]cli.py[51]:preferences_menu() -> [['Server'], None, None]
[02/11/2023 09:24:55 PM][DEBUG][root]cli.py[65]:preferences_menu() -> terminal_menu.chosen_menu_index=1
[02/11/2023 09:24:55 PM][DEBUG][root]cli.py[81]:get_selections() -> possible_values=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
[02/11/2023 09:24:55 PM][DEBUG][root]cli.py[92]:get_selections() -> user_preferences[category]=None
[02/11/2023 09:24:55 PM][DEBUG][root]cli.py[96]:get_selections() -> user_preferences={'roles': ['Server'], 'days': ['Monday'], 'locations': None}
[02/11/2023 09:24:55 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:24:55 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:24:55 PM][DEBUG][root]cli.py[51]:preferences_menu() -> [['Server'], ['Monday'], None]
[02/11/2023 09:24:56 PM][DEBUG][root]cli.py[65]:preferences_menu() -> terminal_menu.chosen_menu_index=2
[02/11/2023 09:24:56 PM][DEBUG][root]cli.py[81]:get_selections() -> possible_values=['Test Resturant']
[02/11/2023 09:24:56 PM][DEBUG][root]cli.py[92]:get_selections() -> user_preferences[category]=None
[02/11/2023 09:24:56 PM][DEBUG][root]cli.py[96]:get_selections() -> user_preferences={'roles': ['Server'], 'days': ['Monday'], 'locations': ['Test Resturant']}
[02/11/2023 09:24:56 PM][DEBUG][root]cli.py[143]:verify_login() -> account.user_id=6053191
[02/11/2023 09:24:56 PM][DEBUG][root]cli.py[23]:main() -> account.first_name='Charles'
[02/11/2023 09:24:56 PM][DEBUG][root]cli.py[51]:preferences_menu() -> [['Server'], ['Monday'], ['Test Resturant']]
[02/11/2023 09:24:58 PM][DEBUG][root]cli.py[65]:preferences_menu() -> terminal_menu.chosen_menu_index=3
[02/11/2023 09:24:58 PM][INFO][werkzeug]_internal.py[224]:_log() -> [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5007
 * Running on http://172.22.33.125:5007
[02/11/2023 09:24:58 PM][INFO][werkzeug]_internal.py[224]:_log() -> [33mPress CTRL+C to quit[0m
